"
This class provides the core API for the GsZeroMQ framework.
"
Class {
	#name : 'GsZeroMQ',
	#superclass : 'Object',
	#category : 'GsZeroMQ-Core-GemStone'
}

{ #category : 'public' }
GsZeroMQ class >> , classDocumentation [
	"This is a class documentation"
]

{ #category : 'instance creation' }
GsZeroMQ class >> new [

	^super new
		initialize;
		yourself.
]

{ #category : 'initialization' }
GsZeroMQ >> initialize [
	""
]
